import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import Providers from "./providers";
import ScrollToTop from "@/components/common/scroll-to-top";
import type { Viewport } from "next";
import { inter } from "@/app/ui/fonts";
import { Toaster } from "sonner";
import StickyHeader from "@/components/common/sticky-header";
import { SpeedInsights } from "@vercel/speed-insights/next";
import Header, { DynamicFooter } from "@/components/common/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased flex flex-col min-h-screen    `}
      >
        <Providers>
          <Header />

          <main className="flex-grow   ">
            <SpeedInsights />
            {children}
          </main>
          <ReactQueryDevtools initialIsOpen={false} />
          <ScrollToTop />
          <Toaster richColors={true} duration={3000} position="top-right" />
          <DynamicFooter />
        </Providers>
      </body>
    </html>
  );
}
