import type { Metadata } from "next";
import "./globals.css";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import Providers from "./providers";
import ScrollToTop from "@/components/common/scroll-to-top";
import type { Viewport } from "next";
import { contentFont, inter } from "@/app/ui/fonts";
import { Toaster } from "sonner";
import { SpeedInsights } from "@vercel/speed-insights/next";
import DynamicHeader from "@/components/common/header";
import DynamicFooter from "@/components/common/dynamic-footer";

export const metadata: Metadata = {
  title: "Newport Sailing Club",
  // description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${inter.className} antialiased flex flex-col min-h-screen ${contentFont.className} `}
      >
        <Providers>
          <DynamicHeader />

          <main className="flex-grow   ">
            <SpeedInsights />

            {children}
          </main>
          <ReactQueryDevtools initialIsOpen={false} />
          <ScrollToTop />
          <Toaster richColors={true} duration={2000} position="top-right" />
          <DynamicFooter />
        </Providers>
      </body>
    </html>
  );
}
